import { useState } from 'react';
import { MODEL_OPTIONS, type Settings } from '../settings';

interface Props {
  settings: Settings;
  onChange: (s: Settings) => void;
}

export default function SettingsPanel({ settings, onChange }: Props) {
  const [showKey, setShowKey] = useState(false);

  return (
    <div className="settings">
      <h1>Settings</h1>

      <div className="card">
        <h2>Claude API</h2>
        <p className="muted small">
          Translations are generated by the Claude API, called directly from your browser. Your key
          is stored only in this browser (localStorage) and sent only to api.anthropic.com. Get a
          key at console.anthropic.com.
        </p>
        <label>
          API key
          <div className="row">
            <input
              type={showKey ? 'text' : 'password'}
              value={settings.apiKey}
              placeholder="sk-ant-…"
              onChange={(e) => onChange({ ...settings, apiKey: e.target.value.trim() })}
            />
            <button onClick={() => setShowKey((s) => !s)}>{showKey ? 'Hide' : 'Show'}</button>
          </div>
        </label>
        <label>
          Model
          <select
            value={settings.model}
            onChange={(e) => onChange({ ...settings, model: e.target.value })}
          >
            {MODEL_OPTIONS.map((m) => (
              <option key={m.id} value={m.id}>
                {m.label}
              </option>
            ))}
          </select>
        </label>
      </div>

      <div className="card">
        <h2>Your language</h2>
        <p className="muted small">
          Translations and explanations are written in this language. Set as default for new books.
        </p>
        <label>
          Native language
          <input
            value={settings.defaultTargetLang}
            onChange={(e) => onChange({ ...settings, defaultTargetLang: e.target.value })}
            placeholder="Polski"
          />
        </label>
      </div>
    </div>
  );
}
